services:
  - type: web
    name: satellite-tracker
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: cd backend && python server.py
    envVars:
      - key: PORT
        value: 3000
